import type { PublicSupplierDetailsDto } from "./types";

export const publicSupplierFixtures: PublicSupplierDetailsDto[] = [
  {
    id: "sup-autoparts-pro",
    slug: "autoparts-pro",
    name: "AutoParts Pro",
    legalName: "AutoParts Pro Sp. z o.o.",
    logoUrl: "https://picsum.photos/seed/partslogo/160/160",
    coverUrl: "https://picsum.photos/seed/partscover/1200/520",
    industry: "Automotive aftermarket",
    categories: ["Car parts", "Consumables"],
    city: "Poznan",
    address: "Glogowska 412, 60-004 Poznan",
    geo: { latitude: 52.3676, longitude: 16.8517 },
    rating: 4.8,
    reviewCount: 142,
    verificationStatus: "verified",
    responseTimeText: "Usually replies in 15 minutes",
    deliveryAvailable: true,
    collectionAvailable: true,
    vmiReady: true,
    serviceRadiusKm: 85,
    shortDescription: "Regional distributor of braking, drivetrain and suspension parts.",
    longDescription:
      "AutoParts Pro supplies workshops and fleet service centers with frequent same-day deliveries, technical support and VMI-ready replenishment agreements.",
    contactEmail: "b2b@autopartspro.example",
    contactPhone: "+48 61 823 45 00",
    openingHours: "Mon-Fri 7:00-18:00, Sat 8:00-14:00",
    serviceArea: "Greater Poland and western Poland",
    deliveryTerms: "Own routes up to three times per day. Free delivery above configured B2B terms.",
    featuredBrands: ["Brembo", "Bosch", "Continental"],
    partnershipOptions: ["VMI replenishment", "SLA delivery windows", "Dedicated account manager"]
  },
  {
    id: "sup-werktools",
    slug: "werktools-polska",
    name: "WerkTools Polska",
    legalName: "WerkTools Polska S.A.",
    logoUrl: "https://picsum.photos/seed/toolslogo/160/160",
    coverUrl: "https://picsum.photos/seed/toolscover/1200/520",
    industry: "Workshop equipment",
    categories: ["Tools", "Workshop equipment"],
    city: "Komorniki",
    address: "Poznanska 88, 62-052 Komorniki",
    geo: { latitude: 52.3362, longitude: 16.8107 },
    rating: 4.7,
    reviewCount: 98,
    verificationStatus: "verified",
    responseTimeText: "Usually replies in 1 hour",
    deliveryAvailable: true,
    collectionAvailable: true,
    vmiReady: false,
    serviceRadiusKm: 250,
    shortDescription: "Professional hand tools, pneumatic tools and workshop cabinets.",
    longDescription:
      "WerkTools supports new workshop openings, equipment standardization and long-term B2B supply programs.",
    contactEmail: "b2b@werktools.example",
    contactPhone: "+48 61 899 12 34",
    openingHours: "Mon-Fri 8:00-17:00",
    serviceArea: "Nationwide courier and selected local delivery routes",
    deliveryTerms: "Parcel dispatch in 24h. Heavy equipment quoted individually.",
    featuredBrands: ["Yato", "Wurth"],
    partnershipOptions: ["Bulk quotation", "Framework contract", "Equipment rollout"]
  },
  {
    id: "sup-cleanchem",
    slug: "cleanchem-professional",
    name: "CleanChem Professional",
    legalName: "CleanChem Professional Sp. z o.o.",
    logoUrl: "https://picsum.photos/seed/chemlogo/160/160",
    coverUrl: "https://picsum.photos/seed/chemcover/1200/520",
    industry: "Industrial chemicals",
    categories: ["Workshop chemicals", "Car care"],
    city: "Lubon",
    address: "Przemyslowa 14, 62-030 Lubon",
    geo: { latitude: 52.3471, longitude: 16.8791 },
    rating: 4.6,
    reviewCount: 73,
    verificationStatus: "verified",
    responseTimeText: "Usually replies in 30 minutes",
    deliveryAvailable: true,
    collectionAvailable: true,
    vmiReady: true,
    serviceRadiusKm: 120,
    shortDescription: "Workshop cleaners, lubricants and professional service chemicals.",
    longDescription:
      "CleanChem provides recurring supply of consumable chemistry with configurable safety stock and replenishment thresholds.",
    contactEmail: "orders@cleanchem.example",
    contactPhone: "+48 61 654 32 10",
    openingHours: "Mon-Fri 8:00-16:00",
    serviceArea: "Western Poland",
    deliveryTerms: "Pallet delivery in 48h. Local milk-run deliveries for contracted customers.",
    featuredBrands: ["Castrol", "Wurth"],
    partnershipOptions: ["VMI replenishment", "Hazardous goods handling", "Monthly consolidated billing"]
  },
  {
    id: "sup-safetycore",
    slug: "safetycore",
    name: "SafetyCore",
    legalName: "SafetyCore Sp. z o.o.",
    logoUrl: "https://picsum.photos/seed/safelogo/160/160",
    coverUrl: "https://picsum.photos/seed/safecover/1200/520",
    industry: "Safety and PPE",
    categories: ["Safety", "Workwear"],
    city: "Swadzim",
    address: "Parkowa 3, 62-080 Swadzim",
    geo: { latitude: 52.4232, longitude: 16.7233 },
    rating: 4.9,
    reviewCount: 65,
    verificationStatus: "verified",
    responseTimeText: "Usually replies in 20 minutes",
    deliveryAvailable: true,
    collectionAvailable: true,
    vmiReady: true,
    serviceRadiusKm: 100,
    shortDescription: "Certified workwear, gloves, masks and workshop safety programs.",
    longDescription:
      "SafetyCore helps workshops standardize PPE, define replenishment cycles and keep branch-level safety stock available.",
    contactEmail: "sales@safetycore.example",
    contactPhone: "+48 61 814 15 16",
    openingHours: "Mon-Fri 7:30-16:30",
    serviceArea: "Greater Poland and Lubusz",
    deliveryTerms: "Courier delivery in 24h. Logo personalization available on request.",
    featuredBrands: ["3M"],
    partnershipOptions: ["VMI replenishment", "SLA delivery windows", "PPE standardization"]
  }
];
