import type { VmiPortalSnapshotDto } from "./types";

export const vmiPortalSnapshotFixture: VmiPortalSnapshotDto = {
  user: {
    name: "Michał Stępień",
    role: "Kierownik oddziału VMI",
    organization: "AutoService Komorniki",
    activeLocationId: "loc-komorniki",
  },
  locations: [
    {
      id: "loc-komorniki",
      name: "Komorniki Warsztat",
      address: "ul. Poznańska 14, 62-052 Komorniki",
    },
    {
      id: "loc-poznan",
      name: "Poznań Punkt Serwisowy",
      address: "ul. Głogowska 120, 60-205 Poznań",
    },
  ],
  vendors: [
    {
      id: "vendor-autoparts",
      name: "AutoParts Pro",
      industry: "Części samochodowe i eksploatacyjne",
      accentColor: "blue",
      connectionStatus: "Aktywny",
      status: "Aktywny",
      accountManager: {
        name: "Tomasz Kowalski",
        phone: "+48 601 234 567",
        email: "t.kowalski@autopartspro.pl",
      },
      contacts: [
        {
          name: "Tomasz Kowalski",
          role: "Główny opiekun",
          phone: "+48 601 234 567",
          email: "t.kowalski@autopartspro.pl",
          status: "online",
        },
        {
          name: "Janusz Nowak",
          role: "Wsparcie techniczne",
          phone: "+48 601 111 222",
          email: "j.nowak@autopartspro.pl",
          status: "online",
        },
      ],
      portfolio: {
        since: "2004",
        about:
          "AutoParts Pro to wiodący dostawca oryginalnych części zamiennych i akcesoriów samochodowych. Działamy w systemie VMI, dostarczając produkty bezpośrednio do warsztatów w czasie krótszym niż 4 godziny.",
        specialties: ["Układy hamulcowe", "Filtry i oleje", "Zawieszenie", "Elektryka samochodowa"],
        certifications: ["ISO 9001:2015", "TÜV Rheinland", "ATE Brake Center"],
      },
      announcements: [
        {
          id: "autoparts-news-1",
          title: "Limitowana Oferta: Dodatkowy rabat 15% na wybrane elementy złączne VMI",
          type: "offer",
          content:
            "Specjalny pakiet rabatowy przygotowany dla Twoich oddziałów handlowych. Wszystkie zamówienia na wybrane śruby, nakrętki oraz podkładki ocynkowane złożone do końca tego tygodnia za pośrednictwem portalu VMI zostaną zrabatowane o dodatkowe 15% netto!",
          badgeText: "PROMOCJA -15%",
        },
        {
          id: "autoparts-news-2",
          title: "Wdrożenie zautomatyzowanych regałów logistycznych VMI Express",
          type: "info",
          content:
            "W przyszłym miesiącu planujemy montaż inteligentnych, zautomatyzowanych regałów magazynowych bezpośrednio w Twoich halach warsztatowych. System będzie zintegrowany ze skanerem kodów kreskowych, dzięki czemu stany inwentaryzacji będą raportowane w czasie rzeczywistym.",
          badgeText: "NOWOŚĆ TECHNICZNA",
        },
      ],
    },
    {
      id: "vendor-werktools",
      name: "WerkTools",
      industry: "Profesjonalne narzędzia i wyposażenie",
      accentColor: "orange",
      connectionStatus: "Aktywny",
      status: "Aktywny",
      accountManager: {
        name: "Andrzej Wiśniewski",
        phone: "+48 602 987 654",
        email: "a.wisniewski@werktools.pl",
      },
      contacts: [
        {
          name: "Andrzej Wiśniewski",
          role: "Kluczowy opiekun",
          phone: "+48 602 987 654",
          email: "a.wisniewski@werktools.pl",
          status: "online",
        },
        {
          name: "Marcin Zieliński",
          role: "Inżynier sprzedaży",
          phone: "+48 602 333 444",
          email: "m.zielinski@werktools.pl",
          status: "offline",
        },
      ],
      portfolio: {
        since: "2011",
        about:
          "WerkTools specjalizuje się w dostarczaniu najwyższej jakości narzędzi ręcznych, pneumatycznych i elektronarzędzi dla wymagających profesjonalistów warsztatowych.",
        specialties: ["Narzędzia ręczne", "Pneumatyka", "Wózki warsztatowe", "Elektronarzędzia"],
        certifications: ["Certyfikat ISO 9001", "Gwarancja WerkLife", "Atesty bezpieczeństwa CE"],
      },
      announcements: [
        {
          id: "werktools-news-1",
          title: "Wyprzedaż zestawów narzędziowych Beta: do -25% do końca miesiąca!",
          type: "offer",
          content:
            "Uzupełnij wyposażenie stanowisk pracy o legendarne zestawy kluczy i wkrętaków marki Beta. Zamówienia składane przez system VMI automatycznie otrzymują 25% upustu. Oferta ważna do wyczerpania zapasów magazynowych.",
          badgeText: "WYPRZEDAŻ -25%",
        },
        {
          id: "werktools-news-2",
          title: "Mobilna kalibracja kluczy dynamometrycznych w Twoim warsztacie",
          type: "info",
          content:
            "Nasz mobilny autobus techniczny odwiedzi Twoje serwisy w przyszły wtorek. Oferujemy bezpłatną kalibrację i certyfikację wszystkich kluczy dynamometrycznych używanych na stanowiskach naprawczych. Zapisz się już dziś!",
          badgeText: "MOBILNY SERWIS",
        },
      ],
    },
    {
      id: "vendor-cleanchem",
      name: "CleanChem",
      industry: "Chemia warsztatowa i środki czyszczące",
      accentColor: "green",
      connectionStatus: "Aktywny",
      status: "Aktywny",
      accountManager: {
        name: "Karolina Nowak",
        phone: "+48 501 111 222",
        email: "k.nowak@cleanchem.com.pl",
      },
      contacts: [
        {
          name: "Karolina Nowak",
          role: "Opiekun handlowy",
          phone: "+48 501 111 222",
          email: "k.nowak@cleanchem.com.pl",
          status: "online",
        },
        {
          name: "Piotr Kaczmarek",
          role: "Dyrektor handlowy",
          phone: "+48 501 555 666",
          email: "p.kaczmarek@cleanchem.com.pl",
          status: "busy",
        },
      ],
      portfolio: {
        since: "2015",
        about:
          "CleanChem to producent innowacyjnych, ekologicznych preparatów czyszczących, odtłuszczaczy i chemii technicznej przeznaczonej dla przemysłu i warsztatów.",
        specialties: ["Zmywacze ekologiczne", "Płyny eksploatacyjne", "Środki BHP i czystości", "Chemia warsztatowa"],
        certifications: ["Normy REACH", "Atest PZH", "ISO 14001:2015"],
      },
      announcements: [
        {
          id: "cleanchem-news-1",
          title: "Premiera: Ekologiczny zmywacz BioClean-15 wolny od LZO",
          type: "info",
          content:
            "Przedstawiamy w pełni biodegradowalny, bezpieczny dla skóry zmywacz montażowy serii BioClean-15. Wyprodukowany na bazie ekstraktów cytrusowych, nie wydziela szkodliwych oparów i doskonale czyści tarcze hamulcowe.",
          badgeText: "EKO NOWOŚĆ",
        },
        {
          id: "cleanchem-news-2",
          title: "Bezpłatna dzierżawa automatycznych stacji dozujących chemię",
          type: "offer",
          content:
            "Chcesz obniżyć zużycie koncentratów myjących? Zainstaluj bezpłatną, automatyczną stację dozującą CleanChem Eco-Mix. Urządzenie precyzyjnie miesza wodę z preparatem, redukując koszty chemii o 35%.",
          badgeText: "ZYSKAJ OSZCZĘDNOŚĆ",
        },
      ],
    },
    {
      id: "vendor-safetycore",
      name: "SafetyCore",
      industry: "Odzież robocza, BHP i ochrona osobista",
      accentColor: "rose",
      connectionStatus: "Aktywny",
      status: "Aktywny",
      accountManager: {
        name: "Mariusz Lewandowski",
        phone: "+48 703 555 444",
        email: "m.lewandowski@safetycore.pl",
      },
      contacts: [
        {
          name: "Marek Jankowski",
          role: "Konsultant techniczny",
          phone: "+48 701 444 555",
          email: "m.jankowski@safetycore.pl",
          status: "online",
        },
        {
          name: "Anna Dąbrowska",
          role: "Dział logistyki",
          phone: "+48 701 888 999",
          email: "a.dabrowska@safetycore.pl",
          status: "online",
        },
      ],
      portfolio: {
        since: "2009",
        about:
          "SafetyCore to Twój zaufany partner w dziedzinie bezpieczeństwa i higieny pracy. Projektujemy i dostarczamy profesjonalną odzież roboczą, obuwie i ochronniki.",
        specialties: ["Odzież robocza BHP", "Obuwie ochronne S3", "Ochrona dróg oddechowych", "Automaty vendingowe BHP"],
        certifications: ["EN ISO 20345", "Certyfikaty OEKO-TEX", "Standard CE Ochrony"],
      },
      announcements: [
        {
          id: "safetycore-news-1",
          title: "Szybka personalizacja odzieży: Haft komputerowy z logo gratis!",
          type: "offer",
          content:
            "Dla wszystkich nowych zamówień na kurtki i spodnie robocze marki SafetyCore oferujemy wykonanie haftu komputerowego z logo Twojego serwisu zupełnie za darmo. Promocja obowiązuje przy zamówieniach powyżej 10 kpl.",
          badgeText: "HAFT GRATIS",
        },
        {
          id: "safetycore-news-2",
          title: "Montaż automatów vendingowych BHP-omat VMI na Twojej hali",
          type: "announcement",
          content:
            "Uruchomiliśmy program pilotażowy montażu automatów BHP-omat. Twoi mechanicy mogą pobierać rękawice robocze, maski i okulary ochronne za pomocą kart pracowniczych. Pełna kontrola zużycia BHP 24/7.",
          badgeText: "BHP VENDING",
        },
      ],
    },
  ],
  inventory: [
    {
      id: "inv-brake-pads",
      vendorId: "vendor-autoparts",
      locationId: "loc-komorniki",
      productName: "Klocki hamulcowe TRW GDB1330",
      vendorSku: "TRW-GDB1330",
      clientSku: "SKU-K-001",
      category: "Układ hamulcowy",
      unit: "kpl.",
      packSize: 4,
      price: 145,
      imageUrl: "https://picsum.photos/seed/trwbrakes/400/300",
      warehouseQty: 128,
      currentStock: 3,
      minStock: 6,
      targetStock: 18,
      incomingQty: 0,
      status: "Below minimum",
      lastUpdated: "2026-07-20T08:30:00.000Z",
    },
    {
      id: "inv-oil-filter",
      vendorId: "vendor-autoparts",
      locationId: "loc-komorniki",
      productName: "Filtr oleju Mann-Filter HU 711/51 x",
      vendorSku: "MANN-HU711",
      clientSku: "SKU-F-020",
      category: "Filtry",
      unit: "szt.",
      packSize: 10,
      price: 28.5,
      imageUrl: "https://picsum.photos/seed/mannfilter/400/300",
      warehouseQty: 244,
      currentStock: 22,
      minStock: 15,
      targetStock: 45,
      incomingQty: 20,
      status: "Healthy",
      lastUpdated: "2026-07-20T09:15:00.000Z",
    },
    {
      id: "inv-gloves",
      vendorId: "vendor-cleanchem",
      locationId: "loc-komorniki",
      productName: "Rekawice nitrylowe GripPro XL",
      vendorSku: "GRIP-XL-100",
      clientSku: "SKU-BHP-011",
      category: "BHP i ochrona",
      unit: "op.",
      packSize: 12,
      price: 78,
      promoPrice: 69,
      imageUrl: "https://picsum.photos/seed/gripgloves/400/300",
      warehouseQty: 52,
      currentStock: 1,
      minStock: 8,
      targetStock: 24,
      incomingQty: 4,
      status: "Approaching minimum",
      lastUpdated: "2026-07-19T13:20:00.000Z",
    },
    {
      id: "inv-wrench-set",
      vendorId: "vendor-werktools",
      locationId: "loc-poznan",
      productName: "Zestaw kluczy Beta 42/S12",
      vendorSku: "BETA-42S12",
      clientSku: "SKU-N-100",
      category: "Narzędzia ręczne",
      unit: "kpl.",
      packSize: 1,
      price: 489,
      promoPrice: 429,
      imageUrl: "https://picsum.photos/seed/betatools/400/300",
      warehouseQty: 18,
      currentStock: 0,
      minStock: 2,
      targetStock: 5,
      incomingQty: 0,
      status: "Out of stock",
      lastUpdated: "2026-07-18T11:05:00.000Z",
    },
    {
      id: "inv-brake-disc",
      vendorId: "vendor-autoparts",
      locationId: "loc-komorniki",
      productName: "Tarcza hamulcowa ATE 24.0122-0150.1",
      vendorSku: "ATE-240122",
      clientSku: "SKU-T-010",
      category: "Układ hamulcowy",
      unit: "szt.",
      packSize: 2,
      price: 198,
      imageUrl: "https://picsum.photos/seed/atediscs/400/300",
      warehouseQty: 76,
      currentStock: 7,
      minStock: 4,
      targetStock: 12,
      incomingQty: 0,
      status: "Healthy",
      lastUpdated: "2026-07-20T10:05:00.000Z",
    },
    {
      id: "inv-brake-cleaner",
      vendorId: "vendor-cleanchem",
      locationId: "loc-komorniki",
      productName: "Zmywacz do hamulców Wurth Brake Cleaner 500ml",
      vendorSku: "WURTH-08901087",
      clientSku: "SKU-C-301",
      category: "Aerozole techniczne",
      unit: "szt.",
      packSize: 24,
      price: 11.2,
      promoPrice: 8.9,
      imageUrl: "https://picsum.photos/seed/wurthclean/400/300",
      warehouseQty: 360,
      currentStock: 11,
      minStock: 24,
      targetStock: 72,
      incomingQty: 24,
      status: "Below minimum",
      lastUpdated: "2026-07-20T12:30:00.000Z",
    },
    {
      id: "inv-castrol-oil",
      vendorId: "vendor-cleanchem",
      locationId: "loc-komorniki",
      productName: "Olej silnikowy Castrol Edge 5W-30 LL 5L",
      vendorSku: "CAST-5W30-5L",
      clientSku: "SKU-C-303",
      category: "Oleje i smary",
      unit: "szt.",
      packSize: 4,
      price: 219,
      imageUrl: "https://picsum.photos/seed/castroloil/400/300",
      warehouseQty: 88,
      currentStock: 18,
      minStock: 12,
      targetStock: 36,
      incomingQty: 0,
      status: "Healthy",
      lastUpdated: "2026-07-20T14:10:00.000Z",
    },
    {
      id: "inv-impact-wrench",
      vendorId: "vendor-werktools",
      locationId: "loc-komorniki",
      productName: "Klucz udarowy akumulatorowy Milwaukee M18 FMTIW2F12",
      vendorSku: "MIL-M18FMTIW",
      clientSku: "SKU-N-201",
      category: "Elektronarzędzia",
      unit: "szt.",
      packSize: 1,
      price: 1199,
      imageUrl: "https://picsum.photos/seed/milwaukeewrench/400/300",
      warehouseQty: 9,
      currentStock: 1,
      minStock: 1,
      targetStock: 3,
      incomingQty: 1,
      status: "Approaching minimum",
      lastUpdated: "2026-07-19T16:45:00.000Z",
    },
  ],
  proposals: [
    {
      id: "proposal-001",
      vendorId: "vendor-autoparts",
      locationId: "loc-komorniki",
      proposalNumber: "PROP-VMI-2026-001",
      date: "2026-07-12",
      status: "Oczekująca",
      expiryDate: "2026-07-25",
      deliveryConditions: "Dostawa VMI Express do Komorniki Warsztat w 24h.",
      notes:
        "Propozycja przygotowana na podstawie spadku stanów poniżej minimum oraz historii zużycia z ostatnich 14 dni.",
      urgentLinesCount: 2,
      totalValue: 2460,
      lines: [
        {
          inventoryItemId: "inv-brake-pads",
          qty: 12,
          originalPrice: 145,
          offeredPrice: 132,
          reason: "Stan spadł poniżej minimum. Uzupełnienie do poziomu docelowego.",
        },
        {
          inventoryItemId: "inv-brake-cleaner",
          qty: 48,
          originalPrice: 11.2,
          offeredPrice: 8.9,
          reason: "Szybkie zużycie w bieżącym tygodniu i aktywna promocja dostawcy.",
        },
        {
          inventoryItemId: "inv-oil-filter",
          qty: 12,
          originalPrice: 28.5,
          offeredPrice: 25.5,
          reason: "Domknięcie zapasu do najbliższego opakowania zbiorczego.",
        },
      ],
    },
    {
      id: "proposal-002",
      vendorId: "vendor-cleanchem",
      locationId: "loc-komorniki",
      proposalNumber: "PROP-VMI-2026-002",
      date: "2026-07-13",
      status: "Oczekująca",
      expiryDate: "2026-07-27",
      deliveryConditions: "Dostawa w standardowym oknie logistycznym CleanChem.",
      notes: "Oferta uwzględnia rabat na produkty promocyjne oraz bieżące minimum półkowe.",
      urgentLinesCount: 1,
      totalValue: 840,
      lines: [
        {
          inventoryItemId: "inv-gloves",
          qty: 24,
          originalPrice: 78,
          offeredPrice: 69,
          reason: "Zapas rękawic zbliża się do poziomu alarmowego.",
        },
        {
          inventoryItemId: "inv-castrol-oil",
          qty: 8,
          originalPrice: 219,
          offeredPrice: 205,
          reason: "Uzupełnienie oleju do docelowego poziomu ekspozycji.",
        },
      ],
    },
  ],
  orders: [
    {
      id: "order-001",
      vendorId: "vendor-autoparts",
      locationId: "loc-komorniki",
      orderNumber: "ZAM-202607-9812",
      date: "2026-07-11",
      status: "W przygotowaniu",
      requestedDeliveryDate: "2026-07-14",
      confirmedDeliveryDate: "2026-07-14",
      origin: "Propozycja uzupełnienia",
      poReference: "PO-KOM-2026-081",
      hasAttachment: false,
      totalValue: 3228,
      lines: [
        { inventoryItemId: "inv-brake-pads", requestedQty: 12, confirmedQty: 12, shippedQty: 0, deliveredQty: 0, price: 145 },
        { inventoryItemId: "inv-oil-filter", requestedQty: 30, confirmedQty: 30, shippedQty: 0, deliveredQty: 0, price: 28.5 },
        { inventoryItemId: "inv-brake-cleaner", requestedQty: 48, confirmedQty: 48, shippedQty: 0, deliveredQty: 0, price: 8.9 },
      ],
      timeline: [
        { status: "Szkic", date: "2026-07-11 08:30", description: "Utworzono automatycznie z propozycji VMI." },
        { status: "Wysłane", date: "2026-07-11 09:15", description: "Zamówienie zatwierdzone i wysłane do AutoParts Pro." },
        { status: "Potwierdzone", date: "2026-07-11 11:30", description: "Dostawca potwierdził dostępność pozycji i termin dostawy." },
        { status: "W przygotowaniu", date: "2026-07-12 14:00", description: "Zamówienie jest pakowane w magazynie centralnym." },
      ],
    },
    {
      id: "order-002",
      vendorId: "vendor-werktools",
      locationId: "loc-komorniki",
      orderNumber: "ZAM-202607-9755",
      date: "2026-07-12",
      status: "Częściowo potwierdzone",
      requestedDeliveryDate: "2026-07-15",
      origin: "Zamówienie ręczne",
      poReference: "PO-KOM-TOOL-09",
      notes: "Klucz udarowy potrzebny na środę do naprawy klienta.",
      hasAttachment: true,
      totalValue: 1199,
      lines: [
        { inventoryItemId: "inv-impact-wrench", requestedQty: 1, confirmedQty: 1, shippedQty: 0, deliveredQty: 0, price: 1199 },
        { inventoryItemId: "inv-wrench-set", requestedQty: 1, confirmedQty: 0, shippedQty: 0, deliveredQty: 0, price: 489 },
      ],
      timeline: [
        { status: "Wysłane", date: "2026-07-12 10:00", description: "Wysłano ręczne zamówienie na narzędzia warsztatowe." },
        { status: "Częściowo potwierdzone", date: "2026-07-13 08:15", description: "Część pozycji czeka na potwierdzenie dostępności WerkTools." },
      ],
    },
    {
      id: "order-003",
      vendorId: "vendor-cleanchem",
      locationId: "loc-komorniki",
      orderNumber: "ZAM-202607-9520",
      date: "2026-07-08",
      status: "Dostarczone",
      requestedDeliveryDate: "2026-07-10",
      confirmedDeliveryDate: "2026-07-10",
      origin: "Propozycja uzupełnienia",
      hasAttachment: false,
      totalValue: 2184,
      lines: [
        { inventoryItemId: "inv-castrol-oil", requestedQty: 8, confirmedQty: 8, shippedQty: 8, deliveredQty: 8, price: 219 },
        { inventoryItemId: "inv-gloves", requestedQty: 6, confirmedQty: 6, shippedQty: 6, deliveredQty: 6, price: 72 },
      ],
      timeline: [
        { status: "Wysłane", date: "2026-07-08 11:00", description: "Zamówienie wysłane do CleanChem." },
        { status: "Wysłane (Kurier)", date: "2026-07-09 13:00", description: "Przesyłka nadana kurierem DPD." },
        { status: "Dostarczone", date: "2026-07-10 10:30", description: "Dostarczono i odebrano w Komorniki Warsztat." },
      ],
    },
  ],
  messageThreads: [
    {
      id: "thread-001",
      vendorId: "vendor-werktools",
      subject: "Niedostępność zestawu Beta w zamówieniu ZAM-202607-9755",
      status: "active",
      relatedObjectType: "order",
      relatedObjectId: "order-002",
      unreadCount: 2,
      lastUpdated: "2026-07-20T15:35:00.000Z",
      messages: [
        {
          id: "message-001",
          sender: "client",
          senderName: "Michał Stępień",
          content: "Dzień dobry, zależy mi na szybkiej wysyłce narzędzi. Czy możecie potwierdzić dostępność zestawu Beta?",
          timestamp: "2026-07-20T14:45:00.000Z",
        },
        {
          id: "message-002",
          sender: "vendor",
          senderName: "Andrzej Wiśniewski",
          content:
            "Dzień dobry. Klucz udarowy wyślemy dziś, ale zestaw Beta wymaga potwierdzenia magazynu centralnego. Dam znać do 16:00.",
          timestamp: "2026-07-20T15:35:00.000Z",
        },
      ],
    },
    {
      id: "thread-002",
      vendorId: "vendor-cleanchem",
      subject: "Korekta progów minimalnych BHP",
      status: "active",
      relatedObjectType: "product",
      relatedObjectId: "inv-gloves",
      unreadCount: 1,
      lastUpdated: "2026-07-20T10:15:00.000Z",
      messages: [
        {
          id: "message-003",
          sender: "vendor",
          senderName: "Karolina Nowak",
          content:
            "Widzę częstsze pobrania rękawic GripPro XL. Proponuję podnieść minimum z 8 do 12 opakowań dla Komornik.",
          timestamp: "2026-07-20T10:15:00.000Z",
        },
      ],
    },
    {
      id: "thread-003",
      vendorId: "vendor-autoparts",
      subject: "Pytanie o zamiennik tarcz ATE",
      status: "active",
      relatedObjectType: "proposal",
      relatedObjectId: "proposal-001",
      unreadCount: 0,
      lastUpdated: "2026-07-18T13:10:00.000Z",
      messages: [
        {
          id: "message-004",
          sender: "client",
          senderName: "Michał Stępień",
          content: "Czy do propozycji możecie dopisać zamiennik Brembo dla tarcz ATE?",
          timestamp: "2026-07-18T12:40:00.000Z",
        },
        {
          id: "message-005",
          sender: "vendor",
          senderName: "Tomasz Kowalski",
          content: "Tak, mamy zgodny zamiennik. Przygotuję wariant w kolejnej propozycji.",
          timestamp: "2026-07-18T13:10:00.000Z",
        },
      ],
    },
  ],
  stockCountRequests: [
    {
      id: "stock-count-001",
      vendorId: "vendor-autoparts",
      locationId: "loc-komorniki",
      title: "Inwentaryzacja klocków i filtrów AutoParts",
      deadline: "2026-07-26",
      status: "Oczekujące",
      inventoryItemIds: ["inv-brake-pads", "inv-oil-filter", "inv-brake-disc"],
    },
    {
      id: "stock-count-002",
      vendorId: "vendor-cleanchem",
      locationId: "loc-komorniki",
      title: "Spis niskich stanów chemii i BHP",
      deadline: "2026-07-27",
      status: "Oczekujące",
      inventoryItemIds: ["inv-brake-cleaner", "inv-gloves", "inv-castrol-oil"],
    },
  ],
};
