-- Generic app attachments
--
-- Tenant-scoped, polymorphic attachments for registered app targets.
-- Files are stored in a private Supabase Storage bucket and are exposed through
-- short-lived signed URLs generated by server actions after target validation.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'app-attachments',
  'app-attachments',
  false,
  26214400,
  ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'application/pdf',
    'text/plain',
    'text/csv',
    'application/json',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
)
ON CONFLICT (id) DO UPDATE
SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE TABLE IF NOT EXISTS public.app_attachments (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  target_type     TEXT        NOT NULL,
  target_id       UUID        NOT NULL,
  bucket_id       TEXT        NOT NULL DEFAULT 'app-attachments',
  storage_path    TEXT        NOT NULL UNIQUE,
  file_name       TEXT        NOT NULL CHECK (char_length(file_name) BETWEEN 1 AND 255),
  content_type    TEXT        NOT NULL,
  size_bytes      BIGINT      NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 26214400),
  checksum        TEXT,
  metadata        JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_by      UUID        NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  deleted_by      UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS app_attachments_target_idx
  ON public.app_attachments (org_id, target_type, target_id, created_at DESC, id DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS app_attachments_org_recent_idx
  ON public.app_attachments (org_id, created_at DESC, id DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS app_attachments_created_by_idx
  ON public.app_attachments (created_by, created_at DESC)
  WHERE deleted_at IS NULL;

ALTER TABLE public.app_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_attachments FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "app_attachments_select" ON public.app_attachments;
CREATE POLICY "app_attachments_select" ON public.app_attachments
  FOR SELECT TO authenticated
  USING (
    deleted_at IS NULL
    AND public.can_access_comment_target(org_id, target_type, target_id, 'select', 'default')
  );

DROP POLICY IF EXISTS "app_attachments_insert" ON public.app_attachments;
CREATE POLICY "app_attachments_insert" ON public.app_attachments
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'app-attachments'
    AND created_by = auth.uid()
    AND deleted_at IS NULL
    AND public.can_access_comment_target(org_id, target_type, target_id, 'insert', 'default')
  );

DROP POLICY IF EXISTS "app_attachments_update" ON public.app_attachments;
CREATE POLICY "app_attachments_update" ON public.app_attachments
  FOR UPDATE TO authenticated
  USING (
    deleted_at IS NULL
    AND public.can_access_comment_target(org_id, target_type, target_id, 'select', 'default')
    AND (
      created_by = auth.uid()
      OR public.can_access_comment_target(org_id, target_type, target_id, 'moderate', 'default')
    )
  )
  WITH CHECK (
    public.can_access_comment_target(org_id, target_type, target_id, 'select', 'default')
    AND (
      created_by = auth.uid()
      OR public.can_access_comment_target(org_id, target_type, target_id, 'moderate', 'default')
    )
  );

DROP POLICY IF EXISTS "app_attachments_delete" ON public.app_attachments;
CREATE POLICY "app_attachments_delete" ON public.app_attachments
  FOR DELETE TO authenticated
  USING (false);

DROP POLICY IF EXISTS "app_attachments_storage_select" ON storage.objects;
CREATE POLICY "app_attachments_storage_select"
  ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'app-attachments'
    AND EXISTS (
      SELECT 1
      FROM public.app_attachments a
      WHERE a.bucket_id = storage.objects.bucket_id
        AND a.storage_path = storage.objects.name
        AND a.deleted_at IS NULL
        AND public.can_access_comment_target(
          a.org_id,
          a.target_type,
          a.target_id,
          'select',
          'default'
        )
    )
  );

DROP POLICY IF EXISTS "app_attachments_storage_insert" ON storage.objects;
CREATE POLICY "app_attachments_storage_insert"
  ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'app-attachments'
    AND (storage.foldername(name))[1] IS NOT NULL
    AND (storage.foldername(name))[2] = auth.uid()::text
    AND public.is_org_member((storage.foldername(name))[1]::uuid)
  );

DROP POLICY IF EXISTS "app_attachments_storage_update" ON storage.objects;
CREATE POLICY "app_attachments_storage_update"
  ON storage.objects
  FOR UPDATE TO authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS "app_attachments_storage_delete" ON storage.objects;
CREATE POLICY "app_attachments_storage_delete"
  ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'app-attachments'
    AND EXISTS (
      SELECT 1
      FROM public.app_attachments a
      WHERE a.bucket_id = storage.objects.bucket_id
        AND a.storage_path = storage.objects.name
        AND (
          a.created_by = auth.uid()
          OR public.can_access_comment_target(
            a.org_id,
            a.target_type,
            a.target_id,
            'moderate',
            'default'
          )
        )
    )
  );

COMMENT ON TABLE public.app_attachments IS
  'Generic tenant-scoped attachments for any registered app target.';
