import { type NextRequest } from "next/server";
import { updateSession } from "@/utils/supabase/proxy";
import createIntlMiddleware from "next-intl/middleware";
import { pathnameWithoutLocale } from "@repo/i18n/middleware-utils";
import { routing } from "./i18n/routing";

const intlMiddleware = createIntlMiddleware(routing);

function needsSupabaseSession(pathname: string): boolean {
  const normalized = pathnameWithoutLocale(pathname, routing.locales);
  return (
    normalized === "/" ||
    normalized.startsWith("/dashboard") ||
    normalized.startsWith("/admin") ||
    normalized.startsWith("/onboarding")
  );
}

export async function proxy(request: NextRequest) {
  // Run next-intl middleware first
  const intlResponse = intlMiddleware(request);

  // Set pathname header for server components
  intlResponse.headers.set("x-pathname", request.nextUrl.pathname);

  if (!needsSupabaseSession(request.nextUrl.pathname)) {
    return intlResponse;
  }

  // Run Supabase session proxy on the updated request
  const response = await updateSession(request);

  // Copy cookies from Supabase to the intl response
  const cookiesToCopy = response.cookies.getAll();

  for (const cookie of cookiesToCopy) {
    const { name, value, ...options } = cookie;
    intlResponse.cookies.set(name, value, options);
  }

  return intlResponse;
}

export const config = {
  // NOTE: Next.js requires `matcher` to be a statically-analyzable literal --
  // "Matcher values must be constants to allow for static analysis at
  // build-time; dynamic values are ignored" (Next.js docs). That means this
  // can't be generated by calling a shared helper at runtime; the pattern
  // itself must stay a literal, duplicated across apps/web, apps/public-web,
  // and apps/vmi-client. See @repo/i18n/middleware-utils for the full
  // reasoning behind the `pl(?:/|$)` exclusion (keep it in sync if
  // routing.defaultLocale ever changes from "pl" in any of the three apps).
  matcher: [
    "/((?!api|auth|_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|manifest.webmanifest|pl(?:/|$)|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};
