"use client";

import { useCallback } from "react";
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useQueryClient,
  type QueryClient,
} from "@tanstack/react-query";
import {
  getConversationAction,
  listChatPeopleAction,
  listConversationsAction,
  listMessagesAction,
  markConversationReadAction,
  sendMessageAction,
  type ChatPerson,
} from "@/app/actions/messages";
import {
  clearUnread,
  flattenMessages,
  upsertMessage,
  type MessagesInfiniteData,
  type PendingChatMessage,
} from "@/lib/messages/cache";
import type {
  ChatConversationDetail,
  ChatConversationSummary,
  ChatMessageCursor,
  ChatMessagesPage,
} from "@/lib/messages/types";

export const messagesKeys = {
  all: ["messages"] as const,
  conversations: (orgId: string) => ["messages", "conversations", orgId] as const,
  conversation: (conversationId: string) => ["messages", "conversation", conversationId] as const,
  thread: (conversationId: string) => ["messages", "thread", conversationId] as const,
  people: (orgId: string) => ["messages", "people", orgId] as const,
};

export function useConversations(orgId: string | null | undefined) {
  return useQuery({
    queryKey: messagesKeys.conversations(orgId ?? ""),
    queryFn: async (): Promise<ChatConversationSummary[]> => {
      const result = await listConversationsAction({ limit: 100 });
      if (!result.success) throw new Error((result as { error: string }).error);
      return result.data;
    },
    enabled: !!orgId,
    staleTime: 30_000,
  });
}

export function useConversation(conversationId: string | null | undefined) {
  return useQuery({
    queryKey: messagesKeys.conversation(conversationId ?? ""),
    queryFn: async (): Promise<ChatConversationDetail> => {
      const result = await getConversationAction({ conversationId });
      if (!result.success) throw new Error((result as { error: string }).error);
      return result.data;
    },
    enabled: !!conversationId,
    staleTime: 60_000,
  });
}

/** Messages of one conversation, newest page first; `fetchNextPage` loads older ones */
export function useMessages(conversationId: string | null | undefined) {
  const query = useInfiniteQuery({
    queryKey: messagesKeys.thread(conversationId ?? ""),
    queryFn: async ({ pageParam }): Promise<ChatMessagesPage> => {
      const result = await listMessagesAction({
        conversationId,
        before: (pageParam as ChatMessageCursor | null) ?? null,
      });
      if (!result.success) throw new Error((result as { error: string }).error);
      return result.data;
    },
    initialPageParam: null as ChatMessageCursor | null,
    getNextPageParam: (lastPage) => lastPage.nextCursor,
    enabled: !!conversationId,
    staleTime: 60_000,
  });
  return { ...query, messages: flattenMessages(query.data as MessagesInfiniteData | undefined) };
}

export function useChatPeople(orgId: string | null | undefined) {
  return useQuery({
    queryKey: messagesKeys.people(orgId ?? ""),
    queryFn: async (): Promise<ChatPerson[]> => {
      const result = await listChatPeopleAction();
      if (!result.success) throw new Error((result as { error: string }).error);
      return result.data;
    },
    enabled: !!orgId,
    staleTime: 5 * 60_000,
  });
}

function setThread(queryClient: QueryClient, conversationId: string, message: PendingChatMessage) {
  queryClient.setQueryData<MessagesInfiniteData>(messagesKeys.thread(conversationId), (data) =>
    upsertMessage(data, message)
  );
}

export interface SendMessageVariables {
  conversationId: string;
  bodyPlain: string;
  bodyRich?: unknown | null;
  attachmentIds?: string[];
  /** Generated by the caller; a retry reuses it so the message is stored once */
  clientId: string;
}

/** Sends with an optimistic message; the stored one replaces it (matched by client id) */
export function useSendMessage(meId: string | null | undefined) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (variables: SendMessageVariables) => {
      const result = await sendMessageAction(variables);
      if (!result.success) throw new Error((result as { error: string }).error);
      return result.data;
    },
    onMutate: (variables) => {
      if (!meId) return;
      setThread(queryClient, variables.conversationId, {
        id: `pending:${variables.clientId}`,
        conversation_id: variables.conversationId,
        author_id: meId,
        kind: "text",
        body_plain: variables.bodyPlain,
        body_rich: variables.bodyRich ?? null,
        mentions: [],
        attachment_ids: variables.attachmentIds ?? [],
        system_event: null,
        client_id: variables.clientId,
        created_at: new Date().toISOString(),
        edited_at: null,
        deleted_at: null,
        pending: true,
      });
    },
    onSuccess: (message) => setThread(queryClient, message.conversation_id, message),
    onError: (_error, variables) => {
      queryClient.setQueryData<MessagesInfiniteData>(
        messagesKeys.thread(variables.conversationId),
        (data) => {
          const pending = flattenMessages(data).find((m) => m.client_id === variables.clientId);
          return pending ? upsertMessage(data, { ...pending, pending: false, failed: true }) : data;
        }
      );
    },
  });
}

/** Marks a conversation read (server + local unread count) */
export function useMarkConversationRead(orgId: string | null | undefined) {
  const queryClient = useQueryClient();
  return useCallback(
    (conversationId: string) => {
      if (!orgId) return;
      queryClient.setQueryData<ChatConversationSummary[]>(
        messagesKeys.conversations(orgId),
        (list) => clearUnread(list, conversationId)
      );
      void markConversationReadAction({ conversationId });
    },
    [orgId, queryClient]
  );
}
