import createIntlMiddleware from "next-intl/middleware";
import { type NextRequest } from "next/server";
import { routing } from "./i18n/routing";

const intlMiddleware = createIntlMiddleware(routing);

export function proxy(request: NextRequest) {
  const response = intlMiddleware(request);
  response.headers.set("x-pathname", request.nextUrl.pathname);
  return response;
}

export const config = {
  // NOTE: Next.js requires `matcher` to be a statically-analyzable literal --
  // "Matcher values must be constants to allow for static analysis at
  // build-time; dynamic values are ignored" (Next.js docs), so this can't be
  // generated by calling a shared helper at runtime. The `pl(?:/|$)`
  // exclusion prevents next-intl's own internal rewrite for unprefixed
  // default-locale requests from re-entering this middleware and causing an
  // infinite redirect loop -- see @repo/i18n/middleware-utils for the full
  // reasoning, and apps/web/src/proxy.ts / apps/public-web/src/proxy.ts for
  // the same fix (keep this literal in sync with those if
  // routing.defaultLocale ever changes from "pl").
  matcher: [
    "/((?!api|_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|manifest.webmanifest|pl(?:/|$)|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};
